MODEL:
  net_dim: 64
  channels: 8
  attn_dim: 512
  num_group: 1
  chn_mult: [1, 2, 4, 8, 16]
  num_heads: 8
  ctrl_dim: 512
DIFFUSION:
  img_size: [16, 16, 16]
  num_bits: 8
OPTIMIZER:
  lr: 0.0008
  wd: 0.0008
  warmup_steps: 1000
  restart_interval: 1000
  lr_decay: 0.9
  min_lr: 0.00001
  plateau_patience: 10
DATASET:
  batch_size: 128
TRAINING:
  mode: color
  accumulate_grad_batches: 4
  precision: 16
  accelerator: gpu
  steps: -1  # infinite
  val_check_interval: 1000
  ckpt_dir: checkpoints_color
